spring.application.name=bringit
# \u6570\u636E\u5B58\u5728\u672C\u5730 data \u6587\u4EF6\u5939\u4E0B\uFF0C\u4E0D\u518D\u6D88\u5931
spring.datasource.url=jdbc:h2:file:./data/bringit;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
